### ISSUE TITLE
Create new tag (because of PHP 8 support)

### ISSUE THREAD

**Issue by jorisvandesande** [freshheads/FHMailerBundle#24]
Hi @bart-van-amelsvoort , @jeffreymoelands , @mishaklomp , could you create a new tag (1.0.1) for this bundle? PHP 8 is not supported by the composer.json file in 1.0.0, but I can see that is is already fixed in the `development` branch :).

Thanks 💙!

**Comment by evertharmeling** [comment]
Mate uhhh 💙!

**Comment by bart-van-amelsvoort** [comment]
Sure thing: https://github.com/freshheads/FHMailerBundle/releases/tag/1.0.1
